import React from 'react'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Features from '../components/Features';
// Features
export const metadata = {
  title: "Features Page",
  description: "Generated by create next app",
};
export default function FeaturesPage() {
  return (

    <div className='container mx-auto py-7 mt-20'>
      <Navbar />


      <div className='container mx-auto py-2'>
        <Features />
      </div>

      <Footer />
    </div>
  );
}
